name: CI/CD

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    uses: PrintNow-Dev/PrintNow/.github/workflows/backend.yml@dev

    with:
      service: "printnow-vendor-service"
      image: "ghcr.io/printnow-dev/printnow-vendor-service"
      trigger: ${{ github.event_name }}

    secrets: inherit